// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGRMJmUszBlljbiovt17uQfVsdGs8uIX8',
    appId: '1:17415261917:web:04408d67d83136e8d45534',
    messagingSenderId: '17415261917',
    projectId: 'flutter-firebase-auth-8dec3',
    authDomain: 'flutter-firebase-auth-8dec3.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-8dec3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR7d_UtD5GyzhCn7SY1UQgwsnesKM14HA',
    appId: '1:17415261917:android:96b95fe4d272b618d45534',
    messagingSenderId: '17415261917',
    projectId: 'flutter-firebase-auth-8dec3',
    storageBucket: 'flutter-firebase-auth-8dec3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPmvNzx1Ha0jhSMAMAzmIVq3ena1Nfp40',
    appId: '1:17415261917:ios:38d44ea4efb1f095d45534',
    messagingSenderId: '17415261917',
    projectId: 'flutter-firebase-auth-8dec3',
    storageBucket: 'flutter-firebase-auth-8dec3.appspot.com',
    iosClientId: '17415261917-12h18g1u80j8psbbppo7j35ckgqcbalk.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyapp1Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPmvNzx1Ha0jhSMAMAzmIVq3ena1Nfp40',
    appId: '1:17415261917:ios:38d44ea4efb1f095d45534',
    messagingSenderId: '17415261917',
    projectId: 'flutter-firebase-auth-8dec3',
    storageBucket: 'flutter-firebase-auth-8dec3.appspot.com',
    iosClientId: '17415261917-12h18g1u80j8psbbppo7j35ckgqcbalk.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyapp1Firebase',
  );
}
